# -*- coding: utf-8 -*-
"""ADS Exp 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12OcpO4Vhsniub6xTB_dEP9ZDwizrZWUg

Clustering
"""

from sklearn import datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.cluster import KMeans

df = datasets.load_iris()
y = df.target
yframe=pd.DataFrame(y)
dfr = pd.DataFrame(data=df.data, 
                  columns=df.feature_names)
dfr["target"] = yframe
dfr

kmeans_model =KMeans(n_clusters=3)
y_kmeans = kmeans_model.fit(dfr[['sepal length (cm)','target']])
dfr['kmeans_3']=kmeans_model.labels_
dfr

plt.scatter(x=dfr['sepal length (cm)'],y=dfr['target'],c = dfr['kmeans_3'])

#Intrinsic Method
from sklearn.metrics import silhouette_score
silhouette_score(X, y_kmeans, metric = 'euclidean')

#Adjusted Rand Index
from sklearn.metrics.cluster import adjusted_rand_score
adjusted_rand_score(y, y_kmeans)

#Mutual Information
from sklearn.metrics.cluster import normalized_mutual_info_score
normalized_mutual_info_score (y, y_kmeans)