# -*- coding: utf-8 -*-
"""Hypothesis Testing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XR6qcbt64JCTcLHr0lpXdtWg_XhYBzVG
"""

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

population = pd.read_csv('/content/drive/My Drive/ADS/diamonds.csv', delimiter=",")

population.head(5)

sample = population.sample(n=40)

# print(sample)
# https://www.reneshbedre.com/blog/z-test-in-python.html

"""# Sample Metrics

"""

sample_mean = sample['price'].mean()
sample_mean

sample_std_deviation = sample['price'].std()
sample_std_deviation

"""# Population Metrics"""

population_mean = population['price'].mean()
population_mean

population_std_deviation = population['price'].std()
population_std_deviation

"""# Hypothesis
### H0 : Average price of diamonds is 3200
### HA : Average price of diamonds is not 3200

z-test (n = 40)
alpha : 0.05
"""

import math
Z_statistic = (sample_mean - population_mean) / (population_std_deviation / math.sqrt(40))
Z_statistic

"""critical value:
1. two / one tailed -> two tailed
2. Level of significance -> 0.05
"""

critical_value = +- 1.64

"""### if z-statistic lies between +1.64 and -1.64 then H0 cannot be rejected
### here, z-statistic lies in given range. hence we do not reject null H0

t-test (n = 20)
"""

sample = population.sample(20)

x_bar = sample['price'].mean()
sample_std_deviation = sample['price'].std()

t_statistic = (x_bar - population_mean) / (sample_std_deviation / math.sqrt(20))
t_statistic

"""two tailed
DOF = 19
"""

t_table = 2.262

# t_statistic < t_table we reject null hypothesis
t_statistic = -1.15
t_table = 2.262

# hence, we reject null hypothesis